# Generated by Django 2.1.7 on 2019-03-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('area', models.CharField(choices=[('CK', 'Черкаська'), ('CH', 'Чернігівська'), ('CV', 'Черівецька'), ('DP', 'Дніпропетровська'), ('DT', 'Донецька'), ('IF', 'Івано-Франківська'), ('KK', 'Харківська'), ('KS', 'Херсонська'), ('KM', 'Хмельницька'), ('KV', 'Київська'), ('KC', 'Київ'), ('KH', 'Кіровоградська'), ('LH', 'Луганська'), ('LV', 'Львівська'), ('MY', 'Микалаївська'), ('OD', 'Одеська'), ('PL', 'Полтавська'), ('RV', 'Рівнинська'), ('SM', 'Сумська'), ('TP', 'Тернопільська'), ('VI', 'Вінницька'), ('VO', 'Волинська'), ('ZK', 'Закарпатська'), ('ZP', 'Запорізька'), ('ZT', 'Житомирська'), ('CR', 'АР Крим'), ('SV', 'Севастополь')], default='VI', max_length=2)),
                ('power', models.IntegerField()),
            ],
        ),
    ]
